### ISSUE TITLE
Missing Texworks Icon

### ISSUE THREAD

**Issue by Milozzy** [moka-project/moka-icon-theme#164]
Hi!
Texworks icon doesn't display... 
it seems some kind of problem with symbolic links as you can see from the screenshot below.

![schermata da 2014-12-02 09 51 31](https://cloud.githubusercontent.com/assets/864646/5259998/4bfc6c28-7a09-11e4-864c-e91afe9fd1c2.png)

Thanks!

**Comment by snwh** [comment]
Fixed
