### ISSUE TITLE
blender icon is missing because of symlink problem

### ISSUE THREAD

**Issue by petervaro** [moka-project/moka-icon-theme#167]
It looks like `Moka/YxY/apps/Blender.png` points to `blender.png`, however `Moka/YxY/apps/blender.png` itself also points to `blender.png` => therefore I think the icon is missing...

**Comment by RavensKrag** [comment]
Any chance for this to be fixed soon?

I had previously gotten around this by using the version in the Ubuntu PPA rather than using this repo directly (all-around a better experience). But the PPA was updated recently, so this error has made it into the stable channel.
