### ISSUE TITLE
Package moka-icon-theme-5.0-11.noarch.rpm is not signed

### ISSUE THREAD

**Issue by mustafaozguner** [moka-project/moka-icon-theme#168]
I opened this issue because package is not signed. Some peope may not be familiar with yum/dnf commands 

Installation steps are : 
1) sudo curl -o /etc/yum.repos.d/moka-stable.repo http://mokaproject.com/packages/rpm/moka-stable.repo
2) sudo dnf install moka-icon-theme --nogpgcheck

I think "--nogpgcheck " flag has to be added to the website untill package is signed.

**Comment by snwh** [comment]
Fixed with the migration to OBS.
