### ISSUE TITLE
Desktop configuration (screenshots) bugged

### ISSUE THREAD

**Issue by readmm** [moka-project/moka-icon-theme#174]
I know that pics part is a bug of eOS, but the matter here is in the options in the bottom
This isn't the first time I've seen the bug
It appears sometimes but always in the Options panel
https://youtu.be/Hj5syhHH0gE
frames that not fits, pixelated icons and the violet scheme when something loads are bugs that must be fixed
I'm sorry, I don't have any pic of these bugs but when I get that I'll post them

**Comment by snwh** [comment]
This is not a valid bug for ```moka-icon-theme``` please re-file it: https://github.com/moka-project/orchis-gtk-theme/issues/
