### ISSUE TITLE
Some icons remain the Gnome yet

### ISSUE THREAD

**Issue by GalaxyLJGD** [moka-project/moka-icon-theme#177]
I just installed OS Freya Moka elementary and Faba and I noticed that some icons are the Gnome
![captura de pantalla de 2015-04-14 14 07 38 2](https://cloud.githubusercontent.com/assets/11948239/7144913/7b21a286-e2b2-11e4-9302-1501f48a80ba.png)

**Comment by snwh** [comment]
You'll need to install ```faba-mono-icons```
