### ISSUE TITLE
Support OSX

### ISSUE THREAD

**Issue by dbkaplun** [moka-project/moka-icon-theme#178]
Would be great if I could use these icons on OSX via LiteIcon! I think PNGs work but .icns would work best.

**Comment by snwh** [comment]
Are you crazy? I've not got time to make and maintain a Mac icon theme. ;)

**Comment by secrettriangle** [comment]
Well, it's already mostly there, maybe just needs a script/packaging. :P

**Comment by snwh** [comment]
It would still rely on a intermediate app. If the OS doesn't support it out of the box I'm not inclined to support it.

**Comment by secrettriangle** [comment]
OSX supports changing icons OOTB, you can right click the app and click Get Info, then drag the icon onto the other icon. There are more scriptable ways but OSX definitely supports changing app icons OOTB. See [tinalatif/flat.icns](https://github.com/tinalatif/flat.icns).
