### ISSUE TITLE
Support for Ubuntu 14.10 is not available.

### ISSUE THREAD

**Issue by jpvelsamy** [moka-project/moka-icon-theme#179]
![screenshot from 2015-04-28 06 30 52](https://cloud.githubusercontent.com/assets/11708768/7361048/398d35a6-ed70-11e4-9c45-f0d25e1fe88a.png)
As I tried to reinstall the purchased version of your theme, the software update center pointed out that the theme is not available for current Ubuntu version and the update center also pointed that I should reach out to you folks.
![screenshot from 2015-04-28 06 30 52](https://cloud.githubusercontent.com/assets/11708768/7361052/451c6234-ed70-11e4-8cdb-1cedc900621b.png)

As I tried to find some support, when I reached your site I have been further asked to file a new issue under this project and hence doing so. Please do the necessary.

**Comment by snwh** [comment]
Your best option is to switch to using the PPA:

```sudo add-apt-repository ppa:moka/daily```
```sudo apt-get update```
```sudo apt-get install orchis-gtk-theme```

I've had a pending update for the USC for months, the review process for updates is abysmally long and even longer since Canonical is shifting efforts to the new Ubuntu store on phones and such.

**Comment by jpvelsamy** [comment]
thanks a bunch sam. will do so.
