### ISSUE TITLE
Small monochrome icons in Gnome shell

### ISSUE THREAD

**Issue by 183amir** [moka-project/moka-icon-theme#181]
Starting with Gnome 3.16, Gnome shell shows small monochrome icons in the top panel. These Icons are available with the default applications of Gnome but other apps are missing these icons.
Would you please consider adding these monochrome icons to your icons.
![screenshot from 2015-05-10 19-46-15](https://cloud.githubusercontent.com/assets/5738695/7553965/51d89ede-f74d-11e4-8eae-c150a1d06162.png)
![screenshot from 2015-05-10 19-47-27](https://cloud.githubusercontent.com/assets/5738695/7553967/69054ae4-f74d-11e4-85ac-d3e1c5b99d18.png)

**Comment by snwh** [comment]
There's nothing I can do about this. Apps that support GNOME's symbolic icons will only have these, many (Firefox included) do not.

**Comment by 183amir** [comment]
If you provide `-symbolic.svg` icons in `/usr/share/icons/Moka/scalable/apps/` folder, Gnome shell will use those icons. Proof:

    cp /usr/share/icons/Adwaita/scalable/apps/system-file-manager-symbolic.svg /usr/share/icons/Moka/scalable/apps/firefox-symbolic.svg

![screenshot from 2015-05-11 20-18-32](https://cloud.githubusercontent.com/assets/5738695/7563749/ebd32f86-f81a-11e4-9847-35c4a2a3c2d9.png)

You might wanna look at [this post](https://plus.google.com/+WorldofGnomeOrg/posts/ZEbfygDA4sk) too.

**Comment by Foggalong** [comment]
@183amir wait... so now icon theme creators basically have to create an entirely new size & style of their app icons just to fit in with GNOME?

**Comment by 183amir** [comment]
@Foggalong It's a request not an order. @snwh could ignore it and I said please consider :)

**Comment by Foggalong** [comment]
@183amir what happens if a theme creator does not do it then? If the theme inherits `gnome` then aren't the `*-symbolic` icons for GNOME apps going to be picked up from there?

**Comment by 183amir** [comment]
What happens is Gnome shell will look for `-symbolic` variant first and if
it doesn't find it it will search for the original one. So, it's up to
application developers or theme creators to provide these icons otherwise
Gnome shell will show the normal icons.
So the answer to your question is yes. It's just like any icon lookup in
themes.

**Comment by Foggalong** [comment]
@183amir Your two paragraphs contradicted each other there :P In an icon theme which inherits `gnome-icon-theme`, but doesn't have the `*-symbolic` icons itself will it:

1. Only check in the selected theme for the panel icons, ignoring them if they're in inherits. This would mean just displaying the normal icons from the selected theme.

2. The standard icon lookup where if not in the selected theme it'll look in the inherits. This would mean that GNOME apps would display the symbolic version while other apps display the normal icons from the selected theme.

**Comment by 183amir** [comment]
Number 2 :-D

**Comment by Foggalong** [comment]
@183amir Ah. That's not really much of a choice then for themes that [inherit GNOME like Numix does](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/index.theme#L6). We'll have to decide whether to stop inheriting GNOME or to design and add the 1500+ icon needed :(

Thanks for bringing this up though, I'd not heard about that

**Comment by 183amir** [comment]
Do you want Gnome shell to always display normal icons instead of symbolic ones even for default Gnome apps? Then, look at [here](https://plus.google.com/+WorldofGnomeOrg/posts/ZEbfygDA4sk).

**Comment by Foggalong** [comment]
If I'm understanding correctly that work around would require people to be using our GTK/GS themes which we avoid with Numix.

**Comment by palob** [comment]
@183amir You might be interested in this Shell extension.
https://github.com/rockon999/appmenu-regular-icons

**Comment by 183amir** [comment]
Thank you but I actually like the symbolic icons.
