### ISSUE TITLE
BUG：minetest-icon.png link target

### ISSUE THREAD

**Issue by pandagxnu** [moka-project/moka-icon-theme#189]
Nice project! 
Is it a bug ?
minetest-icon.png link target is mincraft.png

I think it should be minecraft.png

**Comment by HEXcube** [comment]
**Minetest** icon is no longer `minetest-icon.svg`, it's `mintest.svg` now. Minetest fixed their icon to be freedesktop spec compliant in this commit:
[Rename minetest-icon.svg to minetest.svg](https://github.com/minetest/minetest/commit/c345657289ff64a7e623a264d4c57ac06c3213db)

So, icon is now defined like:
```desktop
[Desktop Entry]
Name=Minetest
GenericName=Minetest
Comment=Multiplayer infinite-world block sandbox
Exec=minetest
Icon=minetest
Type=Application
Categories=Game;
```
See the [desktop file](https://github.com/minetest/minetest/blob/master/misc/minetest.desktop).
