### ISSUE TITLE
render-bitmaps.py do read a custom SVG

### ISSUE THREAD

**Issue by antun3s** [moka-project/moka-icon-theme#196]
I created a icon of urbanterror, but "./render-bitmaps.py" do not render the custom SVG.
SVG: http://pastebin.com/nnQmxs8S
I auditioned, I took a copy of a SVG already junciona, the "ubuntuone.svg" and renamed to "ubuntuonebr.svg"
and the script "./render-bitmaps.py" not read "ubuntuonebr.svg"
Same issue.

**Comment by antun3s** [comment]
I auditioned, I took a copy of a SVG already junciona, the "ubuntuone.svg" and renamed to "ubuntuonebr.svg"
and the script "./render-bitmaps.py" not read "ubuntuonebr.svg"
Same issue.

**Comment by snwh** [comment]
It won't render if it detects the output already exists. You will need to unhide the Baseplate layer and change the icon name before rendering.
