### ISSUE TITLE
Missing Faba Colors for 15.04 and 15.10

### ISSUE THREAD

**Issue by octoquad** [moka-project/moka-icon-theme#200]
Hi,

I see that the faba-colors package is available up until 14.10 which is now EOL. I just downloaded the package to install in 15.10 for faba-lutu. Would it be possible to get this package in for 15.10 and the upcoming 16.04 release?

I downloaded the deb from http://ppa.launchpad.net/moka/stable/ubuntu/pool/main/f/faba-colors/ and it works fine in 15.10.

Thanks

**Comment by snwh** [comment]
I axed Faba-Colors (stopped developing it) a long time ago.

**Comment by octoquad** [comment]
Bummer, I really like Faba Lutu. Thanks for the reply and the hard work you put into this project! :)
