### ISSUE TITLE
PyCharm wrong icon

### ISSUE THREAD

**Issue by DFSko** [moka-project/moka-icon-theme#215]
https://blog.jetbrains.com/pycharm/2015/12/pycharm-5-0-2-update-released-along-with-new-jetbrains-branding/

**Comment by DFSko** [comment]
http://blog.jetbrains.com/pycharm/files/2015/12/PyCharm_400x400_Twitter_logo_white.png

**Comment by snwh** [comment]
Hrm, that new icon is so boring.
