### ISSUE TITLE
Icon Request - Terminix

### ISSUE THREAD

**Issue by gnunn1** [moka-project/moka-icon-theme#220]
I'm the author of Terminix (https://github.com/gnunn1/terminix) a tiling terminal emulator for Linux written in GTK3. I'm a big fan of Moka and while Terminix has an Adwaita style icon I'd leave to see one for Moka, if only for the selfish purpose of being able to use it myself. :) 

The Adwaita icon can be viewed here:

https://github.com/gnunn1/terminix/blob/master/data/icons/source.svg

**Comment by ebkalderon** [comment]
The Terminix project has just been renamed to `Tilix`, so the Moka icon for it no longer works. Anyone willing to prepare a fix for this?
