### ISSUE TITLE
Missing Clear Icon on Search Panel

### ISSUE THREAD

**Issue by lamebird** [moka-project/moka-icon-theme#224]
As the title says, instead of showing clear icon like the Paper does (see the screenshot below), Moka just showing black square icon, which indicates there's missing clear icon files.
Would you consider adding the icon? (sorry for bad image)
![image](https://cloud.githubusercontent.com/assets/19585925/15567901/2e3042e2-2353-11e6-8ef2-8a144a978b0e.png)

**Comment by snwh** [comment]
I've pushed a fix for this.
