### ISSUE TITLE
Icon Request - lantern and tor browser

### ISSUE THREAD

**Issue by giwhub** [moka-project/moka-icon-theme#225]
Hello,this icone theme is awesome!Thanks!

May i request some icons here?

Here they are:

lantern:
link 1:https://github.com/getlantern/lantern
link 2:https://getlantern.org/

tor browser:https://www.torproject.org/download/download-easy.html.en

**Comment by snwh** [comment]
I'm going to assume the icon names are `lantern` and `tor-browser`?

**Comment by giwhub** [comment]
i am not sure the tor browser's.

lantern:

lantern.desktop
[Desktop Entry]
Type=Application
Name=lantern
Exec=lantern
Icon=lantern

lantern's icon:
![lantern](https://cloud.githubusercontent.com/assets/14066437/15623545/776e1d94-24a7-11e6-8283-c86469b4a3c2.png)

tor browser:

start-tor-browser.desktop
[Desktop Entry]
Type=Application
Name=Tor Browser
GenericName=Web Browser
Comment=Tor Browser is +1 for privacy and -1 for mass surveillance
Categories=Network;WebBrowser;Security;
Exec=sh -c '"/home/mine/Desktop/tor-browser_en-US/Browser/start-tor-browser" --detach || ([ !  -x "/home/mine/Desktop/tor-browser_en-US/Browser/start-tor-browser" ] && "$(dirname "$*")"/Browser/start-tor-browser --detach)' dummy %k
X-TorBrowser-ExecShell=./Browser/start-tor-browser --detach
Icon=/home/mine/Desktop/tor-browser_en-US/Browser/browser/icons/mozicon128.png
StartupWMClass=Tor Browser

tor browser's icon:
![mozicon128](https://cloud.githubusercontent.com/assets/14066437/15623674/98496d1e-24a9-11e6-8086-3fa360eecd74.png)

**Comment by giwhub** [comment]
May i request firefox-esr's icon in this issue,or making a new one?

**Comment by snwh** [comment]
@giwhub sure, but I can't directly theme tor browser since its self-contained

**Comment by snwh** [comment]
I've added the lantern icon however

**Comment by giwhub** [comment]
Thanks!
