### ISSUE TITLE
Icon Bug - Cheese, Documents & etc

### ISSUE THREAD

**Issue by ElvisPresly** [moka-project/moka-icon-theme#227]
New name icon
Cheese
Icon=org.gnome.Cheese

Documents
Icon=org.gnome.Documents

Notes
Icon=org.gnome.bijiben

Clocks
Icon=org.gnome.clocks

**Comment by thefirstofthe300** [comment]
I can confirm this issue on Arch Linux Gnome 3.20

**Comment by ebkalderon** [comment]
Agreed, none of these icons work proprerly for me on GNOME 3.20 either.
