### ISSUE TITLE
Gnome Calendar icon

### ISSUE THREAD

**Issue by thefirstofthe300** [moka-project/moka-icon-theme#229]
I am not sure if you already have an icon for it but on my Ubuntu 3.18 install using ppa:moka/stable as my source, the Gnome Calendar icon is the Adwaita icon.

**Comment by ebkalderon** [comment]
@thefirstofthe300 Have you tried compiling the theme straight from Git? The icon [certainly exists](https://github.com/moka-project/moka-icon-theme/blob/master/Moka/48x48/apps/calendar.png) on the repo and the correct alias of [org.gnome.Calendar](https://github.com/moka-project/moka-icon-theme/blob/master/Moka/48x48/apps/org.gnome.Calendar.png) also exists. For reference, I'm running GNOME 3.20 on Arch Linux, and it appears correctly for me.

**Comment by snwh** [comment]
Will make a link.
