### ISSUE TITLE
Consider signing tags and releases

### ISSUE THREAD

**Issue by fossfreedom** [moka-project/moka-icon-theme#232]
Hi there,

  I'm looking at pushing this as a package into Debian (and hence all Debian derived distros such as Ubuntu).

One of the usual questions asked is for consideration that upstream sign both tags and releases in future releases.

   [signing github releases](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)
    [gpg signing](https://help.github.com/articles/signing-tags-using-gpg)

Apparently Debian's policy is also to encourage upstream to sign commits, tags and releases to provide assurance of the stuff being built.

Hence the question - would you consider signing tags and releases in future?

**Comment by snwh** [comment]
@fossfreedom is this necessary?

**Comment by fossfreedom** [comment]
It's not an absolute requirement.  Debian encourage upstream maintainers to do so.  Some are quite willing.  Some do not.  I have to ask the question because debian will ask me what upstream intend or do not intend to do


Get Outlook for Android






On Wed, Jun 8, 2016 at 5:28 PM +0100, "Sam Hewitt" <notifications@github.com> wrote:





@fossfreedom is this necessary?

---

**Comment by snwh** [comment]
To be fair this is just an icon theme there's nothing really that would benefit from the gpg signing.

(I will not get Outlook for Android)

**Comment by fossfreedom** [comment]
Ok cheers😃

**Comment by fossfreedom** [comment]
@snwh 

  quick update - both faba and moka have now been accepted into Debian Unstable.

These should flow into Debian derivatives such as Ubuntu 16.10 automatically now.

If you can do me a favour please?  When you release a new version of faba and moka - please can you ping me so that I can update Debian.  Cheers
