### ISSUE TITLE
I'd like to contribute to making icons. Is there a template file?

### ISSUE THREAD

**Issue by ezra-351** [moka-project/moka-icon-theme#430]
Hi, I've been using the Mint-Y icon pack for a while, and I want to make more application icons for it. I'd prefer to work in GIMP, because I don't have any experience in Inkscape, but I'd be more than willing to learn it if necessary. I currently have it installed as a dependency. Anyway, I wanted to know if there's a template file for making icons, or at least some guidelines, so I don't accidentally end up making something that doesn't fit the theme, by making the corners the wrong size or outline the wrong thickness, etc.

**Comment by snwh** [comment]
Yep there's one in: https://github.com/snwh/moka-icon-theme/tree/master/src/bitmaps

**Comment by ezra-351** [comment]
Alright, thanks!
