### ISSUE TITLE
Request for JetBrains

### ISSUE THREAD

**Issue by chrisenytc** [moka-project/moka-icon-theme#62]
love this icon set and I'd like to request icons for 2 apps:

JetBrains WebStorm and JetBrains RubyMine

I saw you made beautiful icons for PHPStorm and PyCharm. I would like to request the creation of icons for WebStorm and RubyMine.

Thanks.

**Comment by chapati** [comment]
+1 for jetbrains icons. Would be really nice to have.

**Comment by vallovic** [comment]
Since Intellij IDEA and RubyMine are already included, I would really appreciate a WebStorm one. :)

**Comment by snwh** [comment]
@vallovic sure

**Comment by snwh** [comment]
@vallovic any other jetbrains apps?

**Comment by vallovic** [comment]
Well, I personally use DataGrip every now and then too. And found that PHP Storm one is outdated too. Thanks for taking this into consideration!

**Comment by alarsyo** [comment]
@snwh Hey, a bit late to the party but there's also PHPStorm from JetBrains which doesn't have an icon
